language: haxe

sudo: false

branches:
  except:
    - gh-pages

env:
  global:
    - HAXE_PATH=$HOME/haxe_source

install:
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - git clone --depth 1 --branch $TRAVIS_HAXE_VERSION https://github.com/HaxeFoundation/haxe.git $HAXE_PATH
  - pushd $HAXE_PATH
  -   make install_dox
  -   make package_doc
  - popd
  - unzip -o $HAXE_PATH/out/*_doc.zip -d api

script:
  - haxe build.hxml
  - neko Main.n -name Haxe -html-doc api -xml-doc $(haxelib path dox | head -1)/bin/xml -icon haxe.png -out out -clean
  - tar -czf out/haxe.tgz -C out Haxe.docset
  - openssl sha1 out/haxe.tgz
