language: objective-c

branches:
  except:
    - gh-pages

install:
  - brew update
  - brew install phinze/cask/brew-cask
  - brew cask install xquartz
  - brew install haxe --HEAD
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib git hxparse https://github.com/Simn/hxparse.git development src
  - haxelib git hxtemplo https://github.com/Simn/hxtemplo.git master src
  - haxelib git hxargs https://github.com/Simn/hxargs.git
  - haxelib git markdown https://github.com/dpeek/haxe-markdown.git master src
  - haxelib git dox https://github.com/dpeek/dox.git

before_script:
  - cd ~/haxelib/dox/git/
  - haxe run.hxml
  - haxe gen.hxml
  - haxe std.hxml
  - cd $TRAVIS_BUILD_DIR

script:
  - haxe build.hxml
  - neko Main.n -name Haxe -html-doc ~/haxelib/dox/git/bin/pages -xml-doc ~/haxelib/dox/git/bin/xml -icon haxe.png -out out -clean
  - tar -cvzf out/haxe.tgz out/Haxe.docset
